// src/screens/contractor/tabview/wallet/WithdrawAmount/styles.ts

import { Platform, StyleSheet } from 'react-native';
import { horizontalScale, verticalScale, fontSize } from '@styles/mixins';
import colors from '@styles/colors';
import fonts from '@assets/Fonts';

const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: colors.white,
    },
    content: {
        flex: 1,
        paddingHorizontal: horizontalScale(20),
    },
    availableBalanceCard: {
        borderRadius: horizontalScale(20),
        padding: horizontalScale(20),
    },
    earningsCardView: {
        borderRadius: horizontalScale(20),
        marginBottom: verticalScale(20),
    },
    balanceLabel: {
        fontSize: fontSize(14),
        fontFamily: fonts.medium,
        color: 'rgba(255, 255, 255, 0.8)',
        marginBottom: verticalScale(8),
    },
    balanceValue: {
        fontSize: fontSize(32), // Slightly smaller to avoid overflow
        fontFamily: fonts.bold,
        color: colors.white,
    },
    sectionTitle: {
        fontSize: fontSize(16),
        fontFamily: fonts.bold,
        color: colors.black,
        marginBottom: verticalScale(16),
    },
    methodRow: {
        flexDirection: 'row',
        gap: horizontalScale(15),
        marginBottom: verticalScale(24),
    },
    methodCard: {
        flex: 1,
        borderRadius: horizontalScale(15),
        padding: horizontalScale(12), // Reduced for more content room
        borderWidth: 1,
        borderColor: '#E5E7EB',
        position: 'relative',
    },
    selectedMethodCard: {
        borderColor: colors.primary,
        backgroundColor: '#F0EDFF',
    },
    checkIconWrapper: {
        position: 'absolute',
        top: horizontalScale(10),
        right: horizontalScale(10),
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkIcon: {
        width: horizontalScale(24),
        height: horizontalScale(24),
        tintColor: colors.primary,
    },
    methodIconWrapper: {
        width: horizontalScale(40),
        height: horizontalScale(40),
        borderRadius: horizontalScale(10),
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: verticalScale(12),
    },
    methodIcon: {
        width: horizontalScale(20),
        height: horizontalScale(20),
    },
    methodName: {
        fontSize: fontSize(14),
        fontFamily: fonts.bold,
        color: colors.black,
        marginBottom: verticalScale(2),
    },
    methodTime: {
        fontSize: fontSize(12),
        fontFamily: fonts.medium,
        color: colors.textSecondary,
    },
    inputGroup: {
        marginBottom: verticalScale(20),
    },
    inputGroupError: {
        borderColor: colors.red,
        borderWidth: 1,
        borderRadius: horizontalScale(12),
        paddingHorizontal: horizontalScale(10),
        paddingVertical: verticalScale(5),
    },
    errorText: {
        fontSize: fontSize(12),
        fontFamily: fonts.medium,
        color: colors.red,
        marginTop: verticalScale(-10),
        marginBottom: verticalScale(10),
        textAlign: 'right',
    },
    limitText: {
        fontSize: fontSize(12),
        fontFamily: fonts.medium,
        color: colors.gray,
        marginTop: verticalScale(-10),
        marginBottom: verticalScale(10),
        textAlign: 'right',
    },
    inputLabel: {
        fontSize: fontSize(14),
        fontFamily: fonts.bold,
        color: '#888',
        marginBottom: verticalScale(8),
    },
    dropdown: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: horizontalScale(12),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        height: verticalScale(50),
        paddingHorizontal: horizontalScale(15),
    },
    dropdownText: {
        flex: 1,
        fontSize: fontSize(14),
        fontFamily: fonts.medium,
        color: colors.black,
    },
    input: {
        backgroundColor: colors.white,
        borderRadius: horizontalScale(12),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        height: verticalScale(50),
        paddingHorizontal: horizontalScale(15),
        fontSize: fontSize(14),
        fontFamily: fonts.medium,
        color: colors.black,
    },
    feeContainer: {
        backgroundColor: '#F5F3FF',
        borderRadius: horizontalScale(12),
        padding: horizontalScale(12),
        marginBottom: verticalScale(8),
    },
    feeRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoIcon: {
        width: horizontalScale(16),
        height: horizontalScale(16),
        tintColor: colors.primary,
        marginRight: horizontalScale(8),
    },
    feeText: {
        fontSize: fontSize(14),
        fontFamily: fonts.medium,
        color: '#6B7280',
    },
    feeTooltipContainer: {
        position: 'absolute',
        top: '100%',
        left: 0,
        marginTop: verticalScale(-10),
        backgroundColor: colors.white,
        padding: horizontalScale(16),
        paddingVertical: verticalScale(12),
        borderRadius: horizontalScale(8),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
        width: horizontalScale(260),
    },
    feeTooltipArrow: {
        position: 'absolute',
        top: -verticalScale(8),
        left: horizontalScale(20),
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 8,
        borderRightWidth: 8,
        borderBottomWidth: 8,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: colors.white,
    },
    feeTooltipArrowShadow: {
        position: 'absolute',
        top: -verticalScale(9),
        left: horizontalScale(20),
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 8,
        borderRightWidth: 8,
        borderBottomWidth: 8,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: 'rgba(0,0,0,0.05)',
    },
    feeTooltipText: {
        fontSize: fontSize(13),
        fontFamily: fonts.medium,
        color: '#1F2937',
        lineHeight: verticalScale(20),
    },
    submitBtn: {
        backgroundColor: colors.primary,
        borderRadius: horizontalScale(15),
        height: verticalScale(55),
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 'auto',
    },
    submitBtnDisabled: {
        opacity: 0.5,
    },
    submitBtnText: {
        fontSize: fontSize(16),
        fontFamily: fonts.bold,
        color: colors.white,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: horizontalScale(20),
    },
    modalContent: {
        backgroundColor: colors.white,
        borderRadius: horizontalScale(25),
        padding: horizontalScale(24),
        width: '100%',
        alignItems: 'center',
    },
    modalImage: {
        width: horizontalScale(100),
        height: horizontalScale(100),
        marginBottom: verticalScale(24),
    },
    modalTitle: {
        fontSize: fontSize(22),
        fontFamily: fonts.medium,
        color: colors.black,
        textAlign: 'center',
        marginBottom: verticalScale(24),
    },
    modalBtnRow: {
        flexDirection: 'row',
        gap: horizontalScale(15),
    },
    modalBtn: {
        flex: 1,
        height: verticalScale(50),
        borderRadius: horizontalScale(12),
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.primary,
    },
    modalBtnPrimary: {
        backgroundColor: colors.primary,
    },
    modalBtnText: {
        fontSize: fontSize(16),
        fontFamily: fonts.bold,
        color: colors.primary,
    },
    modalBtnTextPrimary: {
        color: colors.white,
    },
    successTitle: {
        fontSize: fontSize(22),
        fontFamily: fonts.medium,
        color: colors.black,
        textAlign: 'center',
        marginBottom: verticalScale(4),
    },
    successSubTitle: {
        fontSize: fontSize(18),
        fontFamily: fonts.medium,
        color: colors.black,
        textAlign: 'center',
        marginBottom: verticalScale(24),
    },
    doneBtn: {
        backgroundColor: colors.primary,
        borderRadius: horizontalScale(12),
        height: verticalScale(50),
        width: '50%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    questionDisplayContainer: {
        marginTop: verticalScale(12),
        backgroundColor: '#F9FAFB',
        borderRadius: horizontalScale(12),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: horizontalScale(16),
    },
    questionDisplayText: {
        fontSize: fontSize(14),
        fontFamily: fonts.bold,
        color: colors.black,
        marginBottom: verticalScale(6),
    },
    answerDisplayText: {
        fontSize: fontSize(14),
        fontFamily: fonts.medium,
        color: colors.textSecondary,
    },
});

export default styles;
