export enum JobStatus {
  UPCOMING = 'Upcoming',
  ACTIVE = 'Active',
  COMPLETED = 'Completed',
  CANCELLED = 'Cancelled',
  EXPIRED = 'Expired',
}

export enum NotificationType {
  DISPUTE_RESOLVED = 'dispute_resolved',
  JOB_INVITE = 'job_invite',
  INVITE_RESPONSE = 'invite_response',
  RATE_PROPOSAL = 'rate_proposal',
  COUNTER_OFFER = 'counter_offer',
  HOURS_ADJUSTED = 'hours_adjusted',
  JOB_COMPLETED = 'job_completed',
  WITHDRAWAL_APPROVED = 'withdrawal_approved',
  WITHDRAWAL_REJECTED = 'withdrawal_rejected',
  PROFILE_APPROVED = 'profile_approved',
  PROFILE_REJECTED = 'profile_rejected',
  CERTIFICATE_APPROVED = 'certificate_approved',
  CERTIFICATE_REJECTED = 'certificate_rejected',
  ACCOUNT_STATUS_UPDATE = 'account_status_update',
  SECURITY_ALERT = 'security_alert',
  DISPUTE_RAISED = 'dispute_raised',
  PAYMENT_INITIATED = 'payment_initiated',
  JOB_CANCELLED = 'job_cancelled',
  APPLICATION_ACCEPTED = 'application_accepted',
  APPLICATION_REJECTED = 'application_rejected',
  CONTRACTOR_CLOCK_IN = 'contractor_clock_in',
  CONTRACTOR_CLOCK_OUT = 'contractor_clock_out',
  INVITATION_ACCEPTED = 'invitation_accepted',
  MATCH_CONFIRMED = 'match_confirmed',
  MATCH_REJECTED = 'match_rejected',
  ESCROW_CREDITED = 'escrow_credited',
  ESCROW_AUTO_RELEASED = 'escrow_auto_released',
  PENDING_RATING = 'pending_rating',
  PROFILE_COMPLETION = 'profile_completion',
  UPCOMING_JOB = 'upcoming_job',
  NEXT_HOUR_JOB_ALERT = 'next_hour_job_alert',
  KYC_APPROVED = 'kyc_approved',
  KYC_REJECTED = 'kyc_rejected',
  KYC_UNDER_REVIEW = 'kyc_under_review',
  BUSINESS_REGISTRATION_APPROVED = 'business_registration_approved',
  BUSINESS_REGISTRATION_REJECTED = 'business_registration_rejected',
  ADD_MONEY_SUCCESS = 'ADD_MONEY_SUCCESS',
  CHAT_MESSAGE = 'chat_message',
}
