// src/constants/strings.ts
import { formatCurrency } from '@utils/currencyUtils';
export const CURRENCY = '$';

const strings = {
  common: {
    back: 'Back',
    error: 'Error',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    select: 'Select',
    description: 'Description',
    skip: 'Skip',
    next: 'Next',
    continue: 'Continue',
    yes: 'Yes',
    no: 'No',
    verify: 'Verify',
    register: 'Register',
    login: 'Login',
    logIn: 'Log In',
    logout: 'Logout',
    signUp: 'Sign Up',
    termsAndConditions: 'Terms & Conditions',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    success: 'Success',
    copiedToClipboard: 'Copied to clipboard!',
    copiedToClipboardSecure: 'Copied! Clipboard clears in 60s for privacy.',
    paid: 'Completed',
    pending: 'Pending',
    failed: 'Failed',
    alreadyHaveAccount: 'Already have an account? ',
    noAccount: 'Don’t have an account? ',
    welcome: 'Welcome!',
    pleaseLogin: 'Please login to access your account',
    emailId: 'Email Id',
    emailAddress: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    logoutQuestion: 'Are you sure you want to logout?',
    passwordChangedLogout: 'Your password has been changed. Please logout.',
    sessionExpiredTitle: 'Session Expired',
    sessionExpiredMessage: 'Your session has expired. Please login again to continue.',
    delete: 'Delete',
    deleteAccount: 'Delete Account',
    updateAccount: 'Update Account',
    deleteQuestion: 'Are you sure you want to delete your account? This action cannot be undone.',
    missingInvitationId: 'Missing Invitation ID',
    deleteAccountConfirmation: 'Are you sure you want to delete this account?',
    deleteAccountFailed: 'Delete account failed',
    deleteAccountSuccess: 'Your account has been successfully deleted. We’re sorry to see you go.',
    proposalSubmitted: 'Proposal Submitted',
    submissionFailed: 'Submission Failed',
    pleaseTryAgain: 'Please try again',
    requestFailed: 'Request Failed',
    somethingWentWrong: 'Something went wrong',
    loginFailed: 'Login Failed',
    tooManyAttemptsTitle: 'Too Many Attempts',
    tooManyAttempts: 'Too many attempts. Please try again later.',
    tryAgainInSeconds: (seconds: number) => `Too many attempts. Please try again in ${seconds} seconds.`,
    tryAgainButton: (seconds: number) => `Try again in ${seconds}s`,
    requestFailedWithStatus: (status: number) => `Request failed with status ${status}`,
    failedToFetchNegotiationData: 'Failed to fetch negotiation data',
    reasonPrefix: 'Reason: ',
    na: 'NA',
    unknown: 'Unknown',
    contentNotFound: 'Content Not Found',
    informationUnavailable: 'The information you are looking for is currently unavailable at the moment.',
    unexpectedError: 'An unexpected error occurred',
    noInternetConnection: 'No internet connection. Please check your network and try again.',
    serverUnreachable: 'Unable to connect right now. Please try again shortly.',
    badGateway: 'The server is currently unavailable. Please try again shortly.',
    lastUpdated: (date: string) => `Last updated: ${date}`,
    addBankAccount: {
      updateBankInfo: 'Update Bank Info',
      addBankAccount: 'Add Bank Account',
      accountHolderName: 'Account Holder Name',
      enterAccountHolderName: 'Enter Account Holder Name',
      bankName: 'Bank Name',
      selectBankFirst: 'Please select bank first',
      branchName: 'Branch Name',
      select: 'Select ',
      accountNumber: 'Account Number',
      routingNumber: 'Routing Number',
      interactiveEmail: 'Interac Email',
      enterEmail: 'Enter Interac Email',
      updateBank: 'Update Bank',
      addAccount: 'Add Account',
      bankUpdatedSuccess: 'Bank account updated successfully',
      bankAddedSuccess: 'Bank account added successfully',
      failedUpdateBank: 'Failed to update bank account',
      failedAddBank: 'Failed to add bank account',
      unexpectedError: 'An unexpected error occurred',
      accountNumberLength: 'Account number must be 14 digits',
      routingNumberLength: 'Routing number must be 8 or 9 digits',
      noBranchesAvailable: 'Selected bank has not valid transit number. Please select another bank.',
    },
    citySelection: {
      selectCity: 'Select City',
      close: 'Close',
      searchPlaceholder: 'Enter city name',
      noDataForSearch: 'No data found for this search',
      noDataAvailable: 'No data available',
    },
    fileDownloader: {
      permissionRequired: 'Permission Required',
      storagePermissionMessage: 'Storage permission is required to download invoices. Please enable it in app settings.',
      invoicePdf: 'Invoice PDF',
      invoiceSavedDownloads: 'Invoice saved to Downloads folder',
      invoiceSavedIos: 'Invoice saved — find it in Files → On My iPhone → GigPay',
      downloadFailed: 'Download failed. Please try again.',
    },
  },
  auth: {
    getStarted: {
      screenTitle: 'Get Started',
      createAccount: 'Create Account',
      clientHeadline: 'Hire Talent. Manage Jobs. Pay Securely.',
      contractorHeadline: 'Secure Jobs. Guaranteed Payments.',
      clientOption: 'I’m a client',
      contractorOption: 'I’m a contractor',
    },
    client: {
      login: {
        screenTitle: 'Welcome!',
        subtitle: 'Please login to access your client account',
      },
      signup: {
        screenTitle: 'Registration',
        orgNameLabel: 'Organization Name',
        fullNameLabel: 'Full Name',
        mobileLabel: 'Mobile Number',
        mobilePlaceholder: 'Enter Mobile Number',
        createPasswordLabel: 'Create Your Password',
        confirmPasswordLabel: 'Confirm Your Password',
        agreeTo: 'Accept ',
        termsAndConditions: 'Terms & Conditions',
        privacyAndPolicy: 'Privacy & Policy',
        and: ' and ',
        subtitle: 'Sign Up to access your account',
        registrationFailed: 'Registration Failed',
      },
      setupOrg: {
        screenTitle: 'Setup Organization',
        sectionTitle: 'Business Details',
        addressLabel: 'Organization Address',
        addressPlaceholder: 'Enter Address',
        categoryLabel: 'Business Category',
        categoryPlaceholder: 'Select Category',
        registrationDocLabel: 'Business Registration Document',
        uploadPlaceholder: 'Upload Your Document Here',
        uploadSubtitles: (maxSize: number | string, unit: string) => `PDF, JPG, JPEG and PNG up to ${maxSize}${unit}`,
        uploadSubTitle: (maxSize: number | string, unit: string) => `PDF, DOC, DOCX up to ${maxSize}${unit}`,

      },
      payment: {
        cardMethod: 'Credit Card',
        bankMethod: 'Bank Account',
        addCardTitle: 'Add Card',
        cardholderLabel: 'Cardholder Name',
        cardholderPlaceholder: 'Enter Cardholder Name',
        cardNumberLabel: 'Card Number',
        expiryLabel: 'Expiry Date',
        expiryPlaceholder: 'MM/YY',
        cvvLabel: 'CVV',
        cvvPlaceholder: '***',
        addBankTitle: 'Add Bank Account',
        accountHolderLabel: 'Account Holder Name',
        accountHolderPlaceholder: 'Enter Account Holder Name',
        bankNameLabel: 'Bank Name',
        bankNamePlaceholder: 'Enter Bank Name',
        accountNumberLabel: 'Account Number',
        accountNumberPlaceholder: 'Enter Account Number',
        routingNumberLabel: 'Routing Number',
        routingNumberPlaceholder: 'Enter Routing Number',
        emptyCardTitle: 'Add Your First Card',
        emptyCardDescription: 'Add your credit card to make secure and seamless payments anytime.',
        emptyBankTitle: 'Add Your Bank Account',
        emptyBankDescription: 'Connect your bank account to transfer money securely and manage payments with ease.',
      },
      forgotPassword: {
        screenTitle: 'Forgot Password',
        emailLabel: 'Email Id',
        emailPlaceholder: 'Enter Email Id',
        submit: 'Submit',
        enterCode: 'Enter Code',
        otpSubtitle: 'We\'ve sent a 6-digit verification code to your Email Id:',
        otpSubtitlePhone: 'We\'ve sent a 6-digit verification code to your Phone Number:',

        expiringIn: 'Expiring in ',
        resendPrompt: 'Didn\'t receive the OTP? ',
        resendAction: 'Resend OTP',
        verify: 'Verify',
      },
      resetPassword: {
        screenTitle: 'Reset Password',
        newPasswordLabel: 'New Password',
        newPasswordPlaceholder: 'Enter New Password',
        confirmPasswordLabel: 'Confirm Your Password',
        confirmPasswordPlaceholder: '********',
        submit: 'Reset Password',
        checklist: {
          title: 'Note: Your Password is strong :',
          minChar: 'Minimum character should be 8.',
          upperCase: 'At least one upper case letter (A-Z).',
          lowerCase: 'At least one lower case letter (a-z).',
          digit: 'There should be one digit (0-9).',
          specialChar: 'At least one special character (e.g. @, #, $, %, &, *)',
        }
      },
      otp: {
        screenTitle: 'Enter Code',
        subtitle: 'We’ve sent a 6-digit verification code to your Email ID:',
        expiringIn: 'Expiring in ',
        resendPrompt: 'Didn\'t receive the OTP? ',
        resendAction: 'Resend OTP',
        verificationFailed: 'Verification Failed',
        resendFailed: 'Failed to resend OTP.',
        emailVerificationFailed: 'Email verification failed',
      }
    },
    contractor: {
      myJobDetails: {
        screenTitle: 'Jobs Details',
        noJobDetails: 'No job details available.',
        untitledJob: 'Untitled Job',
        locationUnknown: 'Location unknown',
        description: 'Description',
        requiredCertification: 'Required Certification',
        requiredContractor: 'Required Contractor:',
        payment: 'Payment',
        attendance: 'Attendance'
      },
      login: {
        subtitle: 'Please login to access your contractor account',
        invalidCredentials: 'user not found',
        somethingWentWrong: 'Something went wrong. Please try again.',
      },
      forgotPassword: {
        screenTitle: 'Forgot Password',
        subtitle: 'Enter your registered email address to receive an OTP to reset your password.',
        submit: 'Submit',
      },
      resetPassword: {
        screenTitle: 'Reset Password',
        subtitle: 'Please enter the OTP sent to your email and your new password.',
        otpLabel: 'OTP Code',
        otpPlaceholder: 'Enter 6-digit OTP',
        newPasswordLabel: 'New Password',
        newPasswordPlaceholder: 'Enter new password',
        confirmPasswordLabel: 'Confirm Password',
        confirmPasswordPlaceholder: 'Confirm new password',
        submit: 'Reset Password',
      },
      signup: {
        subtitle: 'Please register yourself to access your contractor account',
        acceptTerms: 'Accept Terms & Conditions and Privacy & Policy',
        fullName: 'Full Name',
        password: 'Create Your Password',
        confirmPassword: 'Confirm Your Password',
        acceptTermsPrefix: 'Accept ',
        termsAndConditionsLink: 'Terms & Conditions',
        privacyAndPolicyLink: 'Privacy & Policy',
        fullNamePlaceholder: 'Kelvin Doe',
        lastNamePlaceholder: 'Royal',
        passwordPlaceholder: 'XXXXXXXXXX',
        createAccount: 'Create Account',
        registrationSuccessful: 'Registration Successful',
        registrationSuccessfulSub: 'Please verify your email with the OTP sent.',
        registrationFailed: 'Registration Failed',
        somethingWentWrong: 'Something went wrong. Please try again.',
      },
      otp: {
        screenTitle: 'Enter Code',
        subtitle: 'We’ve sent a 6-digit verification code to your Email ID:',
        expiringIn: 'Expiring in ',
        resendPrompt: 'Didn\'t receive the OTP? ',
        resendAction: 'Resend OTP',
        verificationFailed: 'Verification Failed',
        resendFailed: 'Failed to resend OTP.',
        emailVerificationFailed: 'Email verification failed',
        unexpectedError: 'An unexpected error occurred.',
      },
      completeProfile: {
        screenTitle: 'Complete Your Profile',
        step: (current: number, total: number) => `${current} / ${total}`,
        personalInfo: 'Personal Information',
        identityVerification: 'Identity Verification',
        professionalDetails: 'Professional Details',
        bankingDetails: 'Banking Information',
        reviewAndSubmit: 'Review & Submit',
        fullName: 'Full Name',
        genderLabel: 'Gender',
        dobLabel: 'Date of Birth',
        resAddressLabel: 'Address Line 1',
        streetAddressLabel: 'Address Line 2',
        cityLabel: 'City',
        provinceLabel: 'Province',
        postalCodeLabel: 'Postal Code',
        countryLabel: 'Country',
        citizenshipStatusLabel: 'Citizenship Status',
        workPermitLabel: 'Work Permit',
        visaStatusLabel: 'VISA Status',
        jobTitleLabel: 'Job Title',
        experienceLabel: 'Years of Experience',
        skillsLabel: 'Skills',
        serviceOfferedLabel: 'Service Offered',
        hourlyRateLabel: 'Hourly Rate',
        hourlyRatePlaceholder: `e.g. ${CURRENCY}50/hr`,
        bioLabel: 'Bio',
        bioPlaceholder: 'Tell us about yourself...',
        uploadProfilePic: 'Upload Profile Picture',
        documentUpload: 'Document Upload',
        selfieLabel: 'Take a Selfie',
        idFrontLabel: 'ID Front Side',
        idBackLabel: 'ID Back Side',
        idTypeLabel: 'ID Type',
        bankNameLabel: 'Bank Name',
        bankNamePlaceholder: 'Enter Bank Name',
        accountNameLabel: 'Account Holder Name',
        accountNamePlaceholder: 'Enter Account Holder Name',
        accountNumberLabel: 'Account Number',
        accountNumberPlaceholder: 'Enter Account Number',
        routingNumberLabel: 'Routing Number',
        routingNumberPlaceholder: 'Enter Routing Number',
        saveAndContinue: 'Save and Continue',
        identityInformation: 'Identify Information',
        workEligibility: 'Work Eligibility',
        govIdVerification: 'Government ID Verification',
        selectDob: 'Select DOB',
        enterResidentialAddress: 'Enter residential address',
        enterAddress: 'Enter Address',
        enterCity: 'Select City',
        selectCity: 'Select City',
        enterProvince: 'Enter Province',
        enterPostalCode: 'Enter Postal Code',
        enterCountry: 'Enter Country',
        selectCitizenship: 'Select Citizenship Status',
        selectWorkPermit: 'Select Work Permit',
        selectVisaStatus: 'Select Visa Status',
        imageUploadFailed: 'Image upload failed. Please try again.',
        uploadProfilePicture: 'Upload profile picture',
        saveFailedIdentity: 'Failed to save identity information.',
        selfieVerificationLabel: 'Selfie Verification',
        tapToCapture: 'Tap to capture & upload',
        tapToCaptureSelfie: 'Tap to capture face for verification',
        selfieSub: 'Make sure your face is clearly visible',
        jpgPngSize: (maxSize: number | string, unit: string) => `JPG, PNG up to ${maxSize}${unit}`,
        contractorProfileInfo: 'Contractor Profile Information',
        workCategoryLabel: 'Work Category',
        skillsLabelMax: 'Skills (Max 10)',
        skillsPlaceholder: 'Enter Skills',
        experienceLevelLabel: 'Experience Level',
        experienceLevelPlaceholder: 'Enter Experience Level (e.g. 5 Years)',
        hourlyRatePlaceholderNumeric: `Enter Hourly Rate (${CURRENCY})`,
        availabilityLabel: 'Availability',
        availabilityPlaceholder: 'Select Working Days',
        shortBioLabel: 'Short Bio',
        shortBioPlaceholderLong: 'Enter Short Bio',
        uploadResumeLabel: 'Upload Resume (Optional)',
        portfolioLabel: 'Portfolio (Optional)',
        portfolioPlaceholder: 'Enter Portfolio Link',
        selectCertificateLabel: 'Select Certificate',
        uploadLicenseLabel: 'Upload Professional License (Optional)',
        uploadAgreementLabel: 'Upload Agreement (Optional)',
        docSizeLimit: (maxSize: number | string, unit: string) => `PDF, DOC, DOCX up to ${maxSize}${unit}`,
        uploadResumeLimit: (maxSize: number | string, unit: string) => `PDF, DOC, DOCX (Max ${maxSize}${unit})`,
        uploadCertificateLimit: (maxSize: number | string, unit: string) => `PDF, JPG, JPEG, PNG (Max ${maxSize}${unit})`,
        uploadLicenseLimit: (maxSize: number | string, unit: string) => `PDF, JPG, JPEG, PNG (Max ${maxSize}${unit})`,
        uploadAgreementLimit: (maxSize: number | string, unit: string) => `PDF only (Max ${maxSize}${unit})`,
        skillLimitTitle: 'Skill Limit Reached',
        skillLimitMessage: 'You can add up to 10 skill tags.',
        saveFailed: 'Failed to save profile information.',
        uploadFailedDocs: 'Failed to upload documents.',
        uploadYourCertificate: 'Upload Your Certificate',

        // KYC Verification Specifics
        kycVerification: 'KYC Verification',
        verificationSubmitted: 'Verification Submitted',
        verificationSubmittedSub: 'Your identity documents have been submitted successfully.',
        verificationStartError: 'Could not start verification',
        identityVerified: 'Identity Verified',
        identityVerifiedSub: 'Your government ID and selfie verification have been processed successfully. You can now proceed to the next step.',
        verificationFailedTitle: 'Verification Failed',
        rejectionDefault: 'Your documents were rejected. Please try again.',
        rejectionSub: 'We could not verify your identity with the documents provided. Please try again with clear photos.',
        kycDescription: 'To ensure the safety and security of our platform, we require all contractors to verify their identity. Tap the button below to start the secure verification process.',
        howItWorks: 'How it works:',
        howItWorksStep1: 'You will be redirected to our secure verification partner.',
        howItWorksStep2: 'Take a clear photo of your Government ID.',
        howItWorksStep3: 'Complete a quick face scan to verify you are the ID owner.',
        wellLitNote: 'Please ensure you are in a well-lit area and have your physical ID ready.',
        tryAgain: 'Try Again',
        verifyAgain: 'Verify Again',
        startVerification: 'Start Verification',
      },
      home: {
        totalBalanceLabel: 'Total Balance',
        withdraw: 'Withdraw',
        pendingPaymentsSub: 'Payments in process.',
        completedPaymentsSub: 'Payments this month',
        discoverJobs: 'Discover Jobs',
        jobInvitations: 'Job Invitations',
        disputesHistory: 'Disputes History',
        todayJobs: "Today's Jobs",
        upcomingJobs: 'Upcoming Jobs',

        all: "All",
        nearby: "Nearby",
        highestPay: "Highest pay",
        mostRecent: "Most recent",
        noJobsForToday: 'No jobs for today',
        noJobsForTodayDesc: 'There are no jobs scheduled for today.',
        noActiveJobs: 'No Active Jobs Found',
        noActiveJobsDesc: "You don't have any active jobs at the moment.",
        noUpcomingJobs: 'No Upcoming Jobs Found',
        noUpcomingJobsDesc: "You don't have any upcoming jobs at the moment.",
        noCompletedJobs: 'No Completed Jobs Found',
        noCompletedJobsDesc: "You haven't completed any jobs yet.",
        jobRate: (rate: string | number) => `Job Rate: ${formatCurrency(rate)}/h`,
        clockIn: 'Clock In',
        clockOut: 'Clock Out',
        navigation: 'Navigation',
        raiseDispute: 'Raise Dispute',
        disputeTooltipLimit: (hours: number | string) => `The raise dispute window will close in ${hours} hours.`,
        rateClient: 'Rate Client',
        jobRateLabel: 'Job Rate: ',
        proposedRateLabel: 'Proposed Rate: ',
        nagotiontedRate: 'Negotiated Rate: ',
        locationRequired: 'Please turn on location',
        notNearby: 'Looks like you’re not at the job site yet. Move closer to clock in.',
        formatStatus: (status?: string) => {
          if (!status) return '';
          if (status === 'pendingApproval') return 'Pending Approval';
          // Capitalize first letter for other statuses as fallback
          return status.charAt(0).toUpperCase() + status.slice(1);
        },
        clockInOutPopup: {
          clockInSuccess: 'Clocked in successfully',
          clockInFailed: 'Failed to clock in',
          clockOutFailed: 'Failed to clock out',
          notTimeYet: "It's not time to clock in yet.",
          windowClosed: "The job has ended. You cannot clock in.",
          clockInTomorrow: "Please clock in tomorrow at the scheduled shift time.",
          activeJobRunning: "You're still clocked in to a job. Please clock out before starting another.",
          jobCompleted: "This job is already completed for today's time shift",
          somethingWentWrong: 'Something went wrong',
          gpsVerified: 'GPS Verified',
          readyToStart: 'Ready to start your Shift?',
          shiftDuration: 'Shift Duration',
          startedAt: (time: string) => `Started at ${time}`,
          clockInBtn: 'Clock-In',
          clockOutBtn: 'Clock-Out',
          shiftCompleted: 'Shift Completed',
          clockInLabel: 'Clock In',
          clockOutLabel: 'Clock Out',
          totalHoursLabel: 'Total Hours',
          earningLabel: 'Earning',
          paymentStatusLabel: 'Payment Status',
          pendingReview: 'Pending Review',
          na: 'Pending',
          totalHoursValue: (hours: number, minutes: number) => {
            if (hours > 0 && minutes > 0) return `${hours}h ${minutes}m`;
            if (hours > 0) return `${hours}h`;
            return `${minutes}m`;
          },
        }
      },
      highestPay: "Highest Pay",
      mostRecent: "Most Recent",
      kycFailedMessage: 'Your KYC verification process has failed. You can still access and view the application, however, you will not be permitted to apply for jobs. Successful KYC verification is mandatory for job applications.',
      restrictedDuringReview: 'Restricted during kyc verification failed',

      jobInvitations: {
        screenTitle: 'Job Invitation',
        searchPlaceholder: 'Search Jobs by Job Title',
        all: 'All',
        nearby: 'Nearby',
        highestPay: 'Highest Pay',
        mostRecent: 'Most Recent',
        decline: 'Decline',
        accept: 'Accept',
        open: 'Open',
        booked: 'Booked',
        jobRate: (rate: string | number) => `Job Rate: ${formatCurrency(rate)}/h`,
        Proposed: (rate: string | number) => `Proposed Rate: ${formatCurrency(rate)}/h`,
        noJobInvitationsFound: 'No job invitations found',
        noJobInvitationsDesc: 'You do not have any job invitations at the moment.',
        invitationAcceptedSuccess: 'Invitation accepted successfully',
        invitationRejectedSuccess: 'Invitation declined successfully',
        invitationAcceptFailed: 'Failed to accept invitation',
        invitationRejectFailed: 'Failed to decline invitation',
        errorOccurred: 'An error occurred. Please try again.',
      },

      discover: {
        screenTitle: 'Discover Jobs',
        searchPlaceholder: 'Search Jobs by Job Title',
        all: 'All',
        nearby: 'Nearby',
        highestPay: 'Highest pay',
        mostRecent: 'Most recent',
        booked: 'Booked',
        open: 'Open',
        jobRate: (rate: string | number) => `Job Rate: ${formatCurrency(rate)}/h`,
        noJobsFound: 'No jobs found',
        noJobsFoundDesc: 'There are currently no jobs found at the moment.',
      },
      jobDetails: {
        screenTitle: 'Jobs Details',
        jobDetailsNotAvailable: 'Job Details Not Available',
        kycPendingError: 'KYC is pending. Please wait for verification. Go to settings and update your availability.',
        kycPendingMessage: 'KYC is pending. In this case you can only receive jobs but not apply. Please wait for KYC verification.',
        noSpecificCertifications: 'No specific certifications required.',
        proposeRate: 'Propose Rate',
        apply: 'Apply',
        proposeHigherRate: 'Propose Higher Rate',
        proposalRateLabel: `Proposal Rate (${CURRENCY}/hr)`,
        proposalRatePlaceholder: 'Enter Proposal Rate',
        submitProposal: 'Submit Proposal',
        aboutThisJob: 'About this Job',
        description: 'Description',
        requiredCertification: 'Required Certification',
        requiredContractor: 'Required Contractor:',
        assignedContractor: 'Assigned Contractor:',
        decline: 'Decline',
        accept: 'Accept',
        negotiateRate: 'Negotiated Rate',
        negotiateSubtitle: (job: string) => `Enter your counter-offer for ${job}`,
        originalOffer: 'Original Offer',
        yourProposedRate: 'Your Proposed Rate',
        clientProposedRate: 'Client Proposed Rate',
        rejectJob: 'Reject Job',
        acceptJob: 'Accept Job',
        alreadyInvited: 'You have already been invited to this job. Please go to Home → job Invitations and accept the invitation.',
        viewNegotiate: 'View Negotiation',
        alreadyApplied: 'Already applied to this job',
        rateProposed: 'Rate Proposed for This Job',
        proposalRateSentDesc: (rate: string | number) => `Your proposed rate of ${formatCurrency(rate)}/h has been sent.`,
        jobAcceptedTitle: 'Job Accepted',
        invitationDeclinedTitle: 'Invitation Declined',
        jobAddedToListingDesc: 'Job has been added to your listing',
        invitationDeclinedDesc: 'You have declined this invitation',
        pendingOfferTitle: 'Pending Offer',
        pendingOfferDesc: 'Please wait, client offer is pending now',
        noDetailsFoundTitle: 'No Details Found',
        noDetailsFoundDesc: 'Related data not found at the moment.',
        noDescriptionProvided: 'No description provided for this job.',
        scheduleMismatch: "This job's schedule does not match your availability.",
      },
      matches: {
        screenTitle: 'Matches',
        noMatchesTitle: (tab: string) => `No ${tab} Matches`,
        noMatchesDesc: (tab: string) => `You don't have any ${tab.toLowerCase()} matches at the moment.`,
        pending: 'Pending',
        confirmed: 'Confirmed',
        negotiate: 'View Negotiation',
        negotiateSubtitle: (job: string) => `Enter your counter-offer for ${job}`,
        originalOffer: 'Original Offer',
        yourProposedRate: 'Your Proposed Rate',
        clientProposedRate: 'Client Proposed Rate',
        rejectJob: 'Reject Job',
        acceptJob: 'Accept Job',
        clockIn: 'Clock In',
        raiseDispute: 'Raise Dispute',
        hourlyRate: (rate: string | number) => `Hourly Rate: ${formatCurrency(rate)}/h`,
        jobRate: (rate: string | number) => `Hourly Rate: ${formatCurrency(rate)}/h`,
        proposedRate: (rate: string | number) => `Proposed Rate: ${formatCurrency(rate)}/h`,
        negotiatedRate: (rate: string | number) => `Negotiated Rate: ${formatCurrency(rate)}/h`,
      },
      profile: {
        screenTitle: 'Profile',
        accountSettings: 'Account Settings',
        viewProfileDetails: 'View Profile Details',
        certifications: 'Certifications',
        clockOutRequest: 'Clock Out Request',
        bankAccountDetails: 'Bank Account Details',
        ratings: 'Ratings',
        createTransactionPin: 'Create New PIN',
        resetTransactionPin: 'Reset Transaction PIN',
        forgetTransactionPin: 'Forgot Transaction PIN',
        notification: 'Notification',
        applicationSettings: 'Application Settings',
        faq: 'FAQ',
        rateTheApp: 'Rate the App',
        aboutUs: 'About Us',
        support: 'Support',
        deleteAccount: 'Delete Account',
        bankDetails: {
          screenTitle: 'Add Bank Account',
          sectionTitle: 'Add Your Bank Account',
          accountHolderLabel: 'Account Holder Name',
          bankNameLabel: 'Bank Name',
          accountNumberLabel: 'Account Number',
          routingNumberLabel: 'Routing Number',
          accountHolderPlaceholder: 'Enter Account Holder Name',
          bankNamePlaceholder: 'Enter Bank Name',
          accountNumberPlaceholder: 'Enter Account Number',
          routingNumberPlaceholder: 'Enter Routing Number',
          addBtn: 'Add',
        },
        bankAccountList: {
          screenTitle: 'Bank Account Details',
          addNewAccount: 'Add New Account',
          savedBankAccount: 'Saved Bank Account',
          noBankAccountFound: 'No bank account found',
          noDataFoundTitle: 'No Data Found',
          noDataFoundDesc: 'Related data not found at the moment.',
          mockBankName: 'BCA',
          mockAccountNumber: '******** 8907',
        },
        ratingsData: {
          screenTitle: 'Ratings',
          receivedRating: 'Received Rating',
          submittedRating: 'Submitted Rating',
          noReceivedRatingsTitle: 'No ratings received found',
          noReceivedRatingsDesc: "You haven't received any ratings from clients at the moment.",
          noSubmittedRatingsTitle: 'No ratings submitted found',
          noSubmittedRatingsDesc: "You haven't submitted any ratings at the moment.",
          jobTitleLabel: 'Job Title:',
          mockCompany1: 'Tech Corporate',
          mockCompany2: 'Technical Corporate Pvt. Ltd.',
          tagAccuracy: 'Accuracy',
          tagReliability: 'Reliability',
          tagCollaboration: 'Collaboration',
          tagResponsiveness: 'Responsiveness',
        }
      },
      profileDetails: {
        viewTitle: 'View Profile',
        editTitle: 'Edit Profile',
        commissionFee: (fee: string) => `Commission Fee: ${fee}`,
        personalInfo: 'Personal Information',
        fullName: 'Full Name',
        phoneNumber: 'Phone Number',
        emailAddress: 'Email Address',
        dob: 'Date of Birth',
        resAddress: 'Address Line 1',
        professionalInfo: 'Professional Information',
        workCategory: 'Work Category',
        experienceLevel: 'Experience Level',
        hourlyRate: 'Hourly Rate',
        skills: 'Skills',
        availability: 'Availability',
        workEligibility: 'Work Eligibility',
        citizenshipStatus: 'Citizenship Status',
        workPermit: 'Work Permit',
        visaStatus: 'VISA Status',
        portfolio: 'Portfolio',
        addPortfolioUrl: 'Add Portfolio Url',
        docsAndUploads: 'Documents & Uploads',
        resume: 'Resume',
        professionalLicense: 'Professional License',
        contractorAgreement: 'Contractor Agreement',
        editProfile: 'Edit Profile',
        updateChanges: 'Update Changes',
        uploadResume: 'Upload New Resume',
        uploadDoc: 'Upload Document',
        selectCitizenship: 'Select Citizenship Status',
        selectDays: 'Select days',
        addSkill: 'Add skill',
        verified: 'Verified',
        accepted: 'Accepted',
        noFile: 'No file uploaded',
        emailUpdatedTitle: 'Email Updated',
        emailUpdatedDesc: 'You have successfully updated your email. Please logout and login again with your new email.',
      },
      disputes: {
        screenTitle: 'Dispute History',
        byContractor: 'By Contractor',
        forContractor: 'For Contractor',
        searchPlaceholder: 'Search Jobs by Job Title',
        disputeTitle: 'Dispute Title',
        disputeDescription: 'Dispute Description',
        viewAttachment: 'View Attachment',
        attachment: 'Attachment',
        disputeEvidence: 'Dispute Evidence',
        evidenceNotFound: 'Evidence not found',
        disputeTitleValue: 'Payment is delayed',
        statusSettled: 'Settled by Admin',
        noDisputesFound: 'No disputes found',
        noDisputesDescription: "You don't have any dispute at the moment.",
        noDetailsFoundTitle: 'No Disputes Found',
        noDetailsFoundDesc: 'Related data not found at the moment.',
        jobRate: (rate: string | number) => `Job Rate: ${formatCurrency(rate)}/h`,
        requiredCertification: 'Required Certification',
        requiredContractor: 'Required Contractor:',
        all: 'All',
        pending: 'Pending',
        settled: 'Settled',
      },
      wallet: {
        screenTitle: 'Wallet',
        totalEarnings: 'Total Earnings',
        noPenalty: 'No Show Penalty',
        penaltyDeduction: 'No Show Penalty',
        availableBalance: 'Available Balance',
        totalInEscrow: 'Total in ESCROW',
        addMoney: 'Add Money',
        recentJobPayments: 'Recent Job Payments',
        seeAll: 'See all',
        viewEarning: 'View Earning',
        withdrawAmount: 'Withdraw Amount',
        viewTransactionHistory: 'View Transaction History',
        viewEarningSub: 'See your total and detailed earnings',
        withdrawAmountSub: 'Transfer your earnings to your account',
        viewTransactionHistorySub: 'Transfer your earnings to your account',
        viewEarningDetailTitle: 'View Earning',
        noEarningsTitle: 'No Earnings Found',
        noEarningsDesc: "You haven't earned anything yet or no records match your filters.",
        searchJobsPlaceholder: 'Search Jobs by Job Title',
        transactionId: (id: string) => `Transaction ID: ${id}`,
        grossAmountEarned: 'Gross Amount Earned',
        transactionFee: 'Transaction Fee',
        fee: 'Fee',
        disbutFee: 'Dispute Fee',
        netAmount: 'Net Amount',
        jobTime: 'Job Time',
        filterOptions: {
          all: 'All',
          pending: 'Pending',
          success: 'Success',
        },
        jobDate: 'Job Date',
        availableBalanceLabel: 'Available Balance',
        withdrawalMethod: 'Withdrawal Method',
        standard: 'Standard',
        instant: 'Instant',
        standardTime: '1-3 business days',
        instantFee: 'Small fee',
        bankAccount: 'Bank Account',
        noBankAccountAdded: 'No bank account added, please add bank account first',
        selectBank: 'Select Bank',
        loadingBanks: 'Loading banks...',
        withdrawFailed: 'Withdrawal failed. Please try again.',
        withdrawalAmountLabel: 'Withdrawal Amount*',
        enterAmountPlaceholder: 'Enter Amount',
        withdrawalFee: (fee: string) => `Withdrawal Fee ${fee}%`,
        withdrawalFeeNote: 'Total amount receive after the withdrawal fee deduction',
        submit: 'Submit',
        withdrawConfirmTitle: 'Do you want to withdraw ?',
        withdrawSuccessTitle: (amount: string) => `${formatCurrency(amount)} Withdraw Successful`,
        transactionHistoryTitle: 'Transaction History',
        transactionDetailsTitle: 'Transaction Details',
        searchTransactionPlaceholder: 'Search by transaction ID',
        noTransactionsFound: 'No Transactions Found',
        noTransactionsTitle: 'No Transactions Found',
        noTransactionsDesc: "You don't have any transaction history yet.",
        noTransactionDetailsDesc: 'Transaction details are currently not avaliable at the moment.',
        invoiceNumberTitle: 'Invoice Number',
        jobRefTitle: 'Job Ref',
        paidToTitle: 'Paid to',
        paidByTitle: 'Paid By',
        self: 'Self',
        unknownClient: 'Unknown Client',
        hourlyRateTitle: 'Hourly Rate',
        jobRateTitle: 'Job Rate',
        costBreakdownTitle: 'Cost Breakdown',
        totalCostTitle: 'Total Cost',
        bookingFeeTitle: 'Fee',
        netPayableTitle: 'Net Payable',
        securityGuardDefault: 'Security Guard',
        withdrawalAmount: 'Amount',
        bankDetail: 'Bank Detail',
        payoutDate: 'Payout Date',
        payoutStatus: 'Payout Status',
        successful: 'Successful',
        yes: 'Yes',
        no: 'No',
        withdrawSuccessful: 'Withdraw Successful',
        done: 'Done',
        selectBankError: 'Please select a bank account first',
        enterAmountError: 'Please enter a valid amount',
        failedToLoadDetails: 'Failed to load details',
        anErrorOccurred: 'An error occurred',
        transactionTypeLabel: 'Transaction Type:',
        insufficientBalanceError: 'Insufficient available balance',
        securityQuestionLabel: 'Security Question',
        loadingSecurityQuestions: 'Loading security questions...',
        noSecurityQuestions: 'No security questions available',
        selectSecurityQuestion: 'Select Security Question',
        selectQuestionError: 'Please select a security question',
        questionPrefix: 'Question: ',
        answerPrefix: 'Answer: ',
        mobileNumberLabel: 'Mobile Number',
        enterMobileNumberPlaceholder: 'Enter Mobile Number',
        invalidMobileNumberError: 'Please enter a valid 10-digit mobile number.',
        countryCodePlaceholder: 'Code',
        amountRangeError: (min: number | string, max: number | string, currency: string) => `Amount must be between a minimum of ${formatCurrency(min)} and a maximum of ${formatCurrency(max)}`,
        limitText: (min: number | string, max: number | string, currency: string) => `limit: min ${currency}${min} - max ${currency}${max}`,
      },
    },
  },
  client: {
    wallet: {
      screenTitle: 'Wallet',
      availableBalance: 'Available Balance',
      addMoney: 'Add Money',
      recentJobPayments: 'Recent Job Payments',
      seeAll: 'See all',
      noTransactionsTitle: 'No Transactions Found',
      noTransactionsDesc: "You don't have any recent transactions at the moment.",
      noTransactionHistoryDesc: "You don't have any transaction history yet.",
      transactionDetailsTitle: 'Transaction Details',
      noDetailsFound: 'No Details Found',
      noDetailsDesc: 'Transaction details are unavailable at the moment.',
      transactionInformation: 'Transaction Information',
      transactionId: 'Transaction ID',
      invoiceNumber: 'Invoice Number',
      typeLabel: 'Type',
      transactionTypeLabel: 'Transaction Type',
      jobReferenceLabel: 'Job Reference',
      jobTitleLabel: 'Job Title',
      costBreakdownTitle: 'Cost Breakdown',
      jobCostLabel: 'Total Cost',
      bookingFeeLabel: 'Fee',
      transactionFee: 'Transaction Fee',
      penaltyDeduction: 'Penalty Deduction',
      disputeFee: 'Dispute Fee',
      totalPayableLabel: 'Net Payable',
      refundAmount: 'Refund Amount',
      failedToLoadDetails: 'Failed to load details',
      anErrorOccurred: 'An error occurred',
      dateLabel: 'Date',
      timeLabel: 'Time',
      statusLabel: 'Status',
      bankNew: 'Bank New',
      bankDetailsTitle: 'Bank Details',
      bankNameLabel: 'Bank Name',
      holderNameLabel: 'Holder Name',
      totalTransactions: 'Total Transactions',
      enterTransactionPin: 'Please enter the transaction PIN',
      incorrectPin: 'Incorrect transaction PIN',
      verifyPinFailed: 'Failed to verify transaction PIN',
      filterModal: {
        title: 'Filter Transactions',
        status: 'Status',
        transactionType: 'Transaction Type',
        dateRange: 'Date Range',
        startDate: 'Start Date',
        endDate: 'End Date',
        reset: 'Reset',
        applyFilters: 'Apply Filters',
        options: {
          all: 'All',
          successful: 'Successful',
          pending: 'Pending',
          failed: 'Failed',
          allTypes: 'All Types',
          paidToContractor: 'Paid to Contractor',
          addMoney: 'Add Money'
        },
        errors: {
          bothDatesMandatory: 'Both Start and End dates are mandatory',
          futureDates: 'Dates cannot be in the future',
          endDateBeforeStart: 'End date cannot be before Start date',
        }
      }
    },
    jobs: {
      screenTitle: 'Jobs',
      active: 'Active',
      upcoming: 'Upcoming',
      completed: 'Completed',
      addJob: 'Add Job',
      totalEarned: 'Total Earned',
      positionFilled: (f: number, t: number) => `Position Filled: ${f}/${t}`,
      durationHours: (hours: number | string) => {
        const numHours = Number(hours) || 0;
        if (numHours > 0 && numHours < 1) {
          const mins = Math.max(1, Math.round(numHours * 60));
          return `(${mins} ${mins === 1 ? 'min' : 'mins'})`;
        }
        return `(${numHours} ${numHours === 1 ? 'hr' : 'hrs'})`;
      },
      noActiveJobsTitle: 'No Active Jobs Found',
      noActiveJobsDesc: "You don't have any active jobs at the moment.",
      noUpcomingJobsTitle: 'No Upcoming Jobs',
      noUpcomingJobsDesc: 'There are no upcoming jobs found.',
      noCompletedJobsTitle: 'No Completed Jobs',
      noCompletedJobsDesc: 'There are no completed jobs found.',
    },
    jobDetails: {
      screenTitle: 'Job Details',
      description: 'Description',
      requiredCertification: 'Required Certification',
      requiredContractor: 'Required Contractor:',
      appliedContractor: 'Applied Contractor',
      viewAttendance: 'View Attendance',
      paymentHistory: 'Payment History',
      raiseDispute: 'Raise Dispute',
      manualClockIn: 'Manual Clock-in',
      pendingRating: 'Pending Rating',
      open: 'Open',
      notStarted: 'Not Started',
      cancelled: 'Cancelled',
      noContractors: 'No contractors applied yet.',
      scheduledHours: 'Scheduled Hours',
      actualHours: 'Actual Hours',
      noDescriptionProvided: 'No description provided.',
      noDetailsFoundTitle: 'No Details Found',
      noDetailsFoundDesc: 'Related data not found at the moment.',
      jobRate: 'Job Rate:',
      call: 'Call',
      chat: 'Chat',
    },
    attendanceDetails: {
      screenTitle: 'Attendance Details',
      date: 'Date',
      attendance: 'Attendance',
      clockIn: 'Clock In',
      clockOut: 'Clock Out',
      hours: 'Hours',
      onTime: 'On Time',
      noShow: 'No Show',
      totalDays: 'Total Days',
      present: 'Present',
      late: 'Late',
      absent: 'Absent',
      totalHours: 'Total Hours',
      viewAttendance: 'View Attendance',
      noRecords: 'No attendance records found.',
      noDetailsFoundTitle: 'No Details Found',
      noDetailsFoundDesc: 'Related data not found at the moment.',
      hoursCount: (h: number, m: number) => {
        if (h > 0 && m > 0) return `${h}h ${m}m`;
        if (h > 0) return `${h}h`;
        return `${m}m`;
      },
    },
    paymentDetails: {
      screenTitle: 'Payment Details',
      date: 'Date',
      hours: 'Hours',
      rate: 'Rate',
      amount: 'Amount',
      status: 'Status',
      paid: 'Paid',
      pending: 'Pending',
      unpaid: 'Unpaid',
      noRecords: 'No payment records found.',
    },
    paymentsInvoices: {
      screenTitle: 'Payments & Invoices',
      detailsTitle: 'Payment Details',
      searchPlaceholder: 'Search Payments',
      invoiceDownloadSuccess: 'Invoice Download Successfully',
      jobRef: 'Job Ref:',
      totalCost: 'Total Cost',
      bookingFee: 'Fee',
      cancletionFee: 'Cancellation Fee',
      disputeFee: 'Dispute Fee',
      transactionFee: 'Transaction Fee',
      penaltyDeduction: 'Penalty Deduction',
      netPayable: 'Net Payable',
      refundAmount: 'Refund Amount',
      paidTo: 'Paid to',
      paidToBe: 'Paid to be',
      hourlyRate: 'Hourly Rate:',
      costBreakdown: 'Cost Breakdown',
      downloadInvoice: 'Download Invoice',
      invoiceNumber: 'Invoice Number',
      noPaymentsFound: 'No payments found',
      noPaymentsDescription: 'You have no payment history available at the moment.',
      noDetailsFoundTitle: 'No Details Found',
      noDetailsFoundDesc: "We couldn't find the invoice details for this transaction.",
      filterTabs: ['All', 'Pending', 'Success', 'Failed'],
      failedToDownload: 'Failed to download invoice.',
      failedToFetchDetails: 'Failed to fetch details',
      anErrorOccurred: 'An error occurred',
      pending: 'Pending',
      jobTitleFallback: 'Job Title',
      contractorFallback: 'Contractor',
      jobRateLabel: 'Job Rate: ',
      transactionTypeLabel: 'Transaction Type: ',
      jobDate: 'Job Date',
      jobDateLabel: 'Job Date: ',
      iosDownloadLocation: 'Downloaded invoices are saved in the Files app under On My iPhone → GigPay.',
      androidDownloadLocation: 'Downloaded invoices are saved in the device Downloads folder.',
      done: 'Done',
    },
    jobMatches: {
      title: 'Job Matches',
      noMatchesTitle: (tab: string) => `No ${tab} Matches`,
      noMatchesDesc: (tab: string) => `You currently have no ${tab.toLowerCase()} job matches. Check back later for new updates!`,
      pending: 'Pending',
      confirmed: 'Confirmed',
      hourlyRate: 'Hourly Rate:',
      jobRate: 'Job Rate:',
      decline: 'Decline',
      accept: 'Accept',
      jobRef: 'Job Ref:',
      detailsTitle: 'Jobs Details',
      viewNegotiate: 'View Negotiation',
      aboutJob: 'About this Job',
      requiredCertification: 'Required Certification',
      requiredContractor: 'Required Contractor:',
      negotiateRate: 'Negotiated Rate',
      enterCounterOfferFor: 'Enter your counter-offer for',
      originalOffer: 'Original Offer',
      proposedOfferRate: 'Proposed Offer Rate',
      counterOfferRate: 'Counter-Offer Rate',
      enterCounterOfferRate: 'Enter Counter-offer rate',
      counterOfferBtn: 'Counter Offer',
      counterOfferPendingMsg: 'A counter offer has been sent to the contractor. Please wait for their response.',
      proposedRateLabel: (rate: string | number) => `Proposed Rate: ${formatCurrency(rate)}/h`,
      negotiatedRateLabel: (rate: string | number) => `Negotiated Rate: ${formatCurrency(rate)}/h`,
      matchActionSuccess: (action: string) => `Match ${action}ed successfully!`,
      failedToMatchAction: (action: string) => `Failed to ${action} match`,
      errorWhileMatchingAction: (action: string) => `An error occurred while ${action}ing`,
      failedToFetchDetails: 'Failed to fetch details',
      noDetailsFound: 'No Details Found',
      relatedDataNotFound: 'Related data not found at the moment.',
      unknownContractor: 'Unknown Contractor',
      unknownOrganization: 'Unknown Organization',
      unknown: 'Unknown',
      noLocationProvided: 'No location provided',
      noDescriptionProvided: 'No description provided for this job.',
    },
    jobInvites: {
      screenTitle: 'Job Invites',
      detailsTitle: 'Jobs Details',
      searchPlaceholder: 'Search by Job Title & Contractor Name',
      filterOptions: {
        all: 'All',
        pending: 'Pending',
        rejected: 'Rejected',
        accepted: 'Accepted'
      },
      unknownContractor: 'Unknown Contractor',
      noTitle: 'No Title',
      failedToFetch: 'Failed to fetch job invites',
      unexpectedError: 'An unexpected error occurred',
      noJobInvitesFound: 'No Job Invites Found',
      noJobInvitesDesc: "You don't have any job invites sent or received at the moment.",
      noDetailsFoundTitle: 'No Details Found',
      noDetailsFoundDesc: 'Related data not found at the moment.',
      hourlyRate: 'Hourly Rate:',
      jobRate: 'Job Rate:',
      aboutJob: 'About this Job',
      requiredCertification: 'Required Certification',
      requiredContractor: 'Required Contractor:',
    },
    jobAwaitingApproval: {
      title: 'Job Awaiting Approval',
      searchPlaceholder: 'Search by Job Title & Contractor Name',
      adjustHours: 'Adjust hours',
      markAsComplete: 'Mark as Complete',
      completed: 'Completed',
      detailsTitle: 'Jobs Details',
      contractorWorkerHours: 'Contractor worked hours',
      clientApprovedHours: 'Client approved hours',
      submit: 'Submit',
      assignedContractor: 'Assigned Contractor:',
      aboutJob: 'About this Job',
      requiredCertification: 'Required Certification',
      requiredContractor: 'Required Contractor:',
      jobRate: 'Job Rate:',
      hoursExceedError: 'Please enter valid hours between 1 and 24.',
      noJobsAwaitingApproval: 'No jobs awaiting approval',
      noJobsAwaitingApprovalDesc: "You're all caught up! We'll let you know when there's something new.",
      unexpectedError: 'An unexpected error occurred',
      markCompleteSuccess: 'Marked as complete successfully.',
      markCompleteFailed: 'Failed to mark as complete.',
      errorOccurred: 'An error occurred',
      hoursAdjustedSuccess: 'Hours adjusted successfully.',
      hoursAdjustFailed: 'Failed to adjust hours.',
      loadDetailsFailed: 'Failed to load details',
      noDetailsFound: 'No Details Found',
      relatedDataNotFound: 'Related data not found at the moment.',
      unknownContractor: 'Unknown Contractor',
      unknownRole: 'Unknown Role',
      locationNotSpecified: 'No location provided',
      dateNotSpecified: 'No date provided',
      timeNotSpecified: 'No time provided',
      noDescription: 'No description provided for this job.',
      noCertificationsRequired: 'No Certifications Required',
      hourlyRateLabel: `Hourly Rate: `,
      unknown: 'Unknown',
      jobRole: 'Job Role',
      zeroRateFallback: `${CURRENCY}0/h`,
      pendingFallback: 'Pending',
      completing: 'Completing...',
      defaultContractorHours: '0 hours',
      enterApprovedHours: 'Enter Approved Hours',
    },
    raiseDispute: {
      screenTitle: 'Raise Dispute',
      contractorName: 'Contractor Name',
      categoryList: 'Dispute Category',
      selectCategory: 'Select Category',
      categoryRequired: 'Dispute category is required',
      cetegoryList: 'Select Cetegory',
      selectContractor: 'Select Contractor Name',
      selectCetegory: 'Select Cetegory',
      subject: 'Subject',
      enterSubject: 'Enter Subject',
      uploadImage: 'Upload Image',
      uploadImageOnly: 'Upload Image Only',
      imageSizeLimit: (minSize: number | string, minUnit: string, maxSize: number | string, maxUnit: string) => `Size- Min ${minSize}${minUnit.toLowerCase()}, Max ${maxSize}${maxUnit.toUpperCase()} | Format- jpeg, png`,
      videosNotAllowed: 'Videos are not allowed',
      description: 'Description',
      enterDescription: 'Enter Description',
      disputeWindowNote: (hours: number | string) => `• The dispute window will close within ${hours} hours after the job ends.`,
      adminAuthorityNote: '• Admin has authority to take action on the raised dispute.',
      deductionNote: '• Some fee may be deducted from the disputed amount.',
      submit: 'Submit',
      subjectValidationInvalidChars: 'Only letters, numbers, and basic symbols (- _ . & ( )) are allowed',
      subjectValidationLength: 'Subject must be between 5 and 100 characters',
      subjectValidationWords: 'Subject must contain between 3 and 100 words',
      descriptionValidationLength: 'Description must be between 20 and 2000 characters',
      descriptionValidationWords: 'Description must contain between 5 and 20 words',
      contractorRequired: 'Contractor selection is required',
      subjectRequired: 'Subject is required',
      descriptionRequired: 'Description is required',
      raiseDisputeSuccess: 'Dispute raised successfully',
      raiseDisputeFailed: 'Failed to raise dispute',
      failedToGetUploadUrl: 'Failed to get upload URL',
      uploadFailed: 'Upload failed',
      actionLabel: 'Select an Option',
      leaveJobNow: 'Leave the job now',
      leaveAfterResolve: 'Leave the job after the dispute is resolved',
      continueJob: 'Continue the job',
      optionRequired: 'Please select an option',
    },
    manualClockIn: {
      screenTitle: 'Manual Clock-in',
      selectContractor: 'Select Contractor Name',
      clockInTime: 'Clock-in Date',
      enterTime: 'Enter Clock-in Time',
      confirm: 'Confirm Clock-in',
    },
    rating: {
      screenTitle: 'Rating',
      selectContractor: 'Select Contractor Name',
      selectRatings: 'Select Ratings',
      excellent: 'Excellent',
      categories: 'Categories',
      overallPerformance: 'Overall Work Performance',
      timeliness: 'Timeliness',
      communication: 'Communication',
      quality: 'Quality',
      accuracy: 'Accuracy',
      professionalism: 'Professionalism',
      deadlines: 'Deadlines',
      reliability: 'Reliability',
      responsiveness: 'Responsiveness',
      clarity: 'Clarity',
      collaboration: 'Collaboration',
      submit: 'Submit',
    },
    home: {
      greeting: 'Hello',
      escrowLabel: 'Total in ESCROW',
      quickActions: 'Quick Actions',
      recentPayments: 'Recent Job Payments',
      seeAll: 'See all',
      progress: 'Job Progress',
      scheduled: 'Job Scheduled',
      jobInvites: 'Job Invites',
      pending: 'Job Pending',
      createJob: 'Create\nJob',
      jobMatches: 'Job\nMatches',
      paymentInvoices: 'Payment &\nInvoices',
      disputesHistory: 'Disputes\nHistory',
      accountVerificationInProgress: 'Account verification in progress. You can create jobs once admin approves your business document.',
      noRecentPaymentsTitle: 'No Recent Payments',
      noRecentPaymentsDesc: 'There are no recent payments at a Moments.',
      setPinSuccess: 'Transaction PIN set successfully',
      setPinFailed: 'Failed to set transaction PIN',
    },
    createJob: {
      screenTitle: 'Create Job Posting',
      jobInfo: 'Job Information',
      jobTitle: 'Job Title',
      jobTitlePlaceholder: 'Enter Job Title',
      jobDescription: 'Job Description',
      jobDescriptionPlaceholder: 'Enter Job Description',
      jobLocation: 'Job Location',
      jobLocationPlaceholder: 'Enter Job Location',
      contractorsRequired: 'Contractors Required',
      contractorsPlaceholder: 'Enter Contractors Required',
      requiredCertification: 'Required Certification',
      requiredCertificationPlaceholder: 'Select Required Certification',
      startDate: 'Start Date',
      endDate: 'End Date',
      startTime: 'Start Time',
      endTime: 'End Time',
      selectPlaceholder: 'Select',
      hourlyPayRate: 'Hourly Pay Rate',
      payRatePlaceholder: 'Enter Hourly Pay Rate',
      editNoticeNote: 'Note: ',
      editNoticeFull: 'You can edit the job title, description, contractor count, dates, and times.',
      editNoticePartial: 'You can only edit the job description and contractor count.',
      documentUploadTitle: 'Post Order Document Upload(optional)',
      uploadDocuments: 'Upload Documents',
      uploadSubtitle: (maxSize: number | string, unit: string) => `PDF, DOC, DOCX up to ${maxSize}${unit}`,
      saveAsDraft: 'Save as Draft',
      preview: 'Preview',
      inviteContractor: 'Invite Contractor',
      jobPost: 'Job Post',
      requiredContractorLabel: 'Required Contractor:',
      noDescription: 'No description provided.',
      noCertifications: 'No certifications mandatory.',
      defaultCompanyName: 'Tech Corporate',
      jobRateLabel: 'Job Rate:',
      maxDocumentsAllowed: 'Maximum 3 documents allowed',
      uploadFailed: 'Upload Failed',
      couldNotUpload: (fileName: string) => `Could not upload ${fileName}`,
      minWordsDesc: 'Description must be at least 10 words',
      contractorMandatory: 'Enter contractor mandatory',
      insufficientBalanceTitle: 'Insufficient Balance',
      insufficientBalanceDesc: 'Your wallet balance is insufficient to post this job. Please add funds to continue.',
      addMoney: 'Add Money',
      cancel: 'Cancel',
      maxContractorsAllowed: (max: number) => `Maximum ${max} contractors allowed per job`,
      discardChangesTitle: 'Discard Changes?',
      discardChangesSub: 'Are you sure you want to go back? You will lose this job details.',
      discardChangesConfirm: 'Yes, Go Back',
      discardChangesCancel: 'Cancel',
      endDateBeforeStart: 'End date cannot be before start date',
      startDateTomorrow: 'Start date must be from tomorrow onwards',
      startTimePast: 'Start time cannot be in the past',
      endTimePast: 'End time cannot be in the past',
      timeDifference: 'Start time and end time must have at least 1 hour difference',
      hourlyRateMandatory: 'Hourly rate is mandatory',
      minHourlyRate: 'Hourly pay rate must be at least 1',
      success: 'Success',
      jobSavedDraft: 'Job saved as draft successfully!',
      failedSaveDraft: 'Failed to save draft',
      somethingWentWrong: 'Something went wrong',
      jobUpdatedSuccess: 'Job updated successfully!',
      failedUpdateJob: 'Failed to update job',
      updateBtn: 'Update',
      editJobTitle: 'Edit Job',
      fileSelected: 'file(s) selected',
      successModal: {
        title: 'Job Post Successful',
        description: 'Your job has been posted successfully.',
        buttonText: 'Invite Contractors',
      },
    },
    profile: {
      screenTitle: 'Profile',
      accountSettings: 'Account Settings',
      viewProfileDetails: 'View Profile Details',
      logout: 'Logout',
      ratings: 'Ratings',
      changePassword: 'Change Password',
      createTransactionPin: 'Create New PIN',
      resetTransactionPin: 'Reset Transaction PIN',
      forgetTransactionPin: 'Forgot Transaction PIN',
      sameTransactionPinError: 'New PIN cannot be the same as your old PIN. Please choose a different PIN.',
      changePinSuccess: 'Transaction PIN changed successfully',
      changePinFailed: 'Failed to change transaction PIN',
      paymentMethods: 'Payment Methods',
      notification: 'Notification',
      applicationSettings: 'Application Settings',
      aboutUs: 'About Us',
      contactUs: 'Contact Us',
      rateTheApp: 'Rate the App',
      support: 'Support',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      deleteAccount: 'Delete Account',
      cardDetails: {
        screenTitle: 'Card Details',
        addNewAccount: 'Add New Account',
        savedCreditCard: 'Saved Credit Card',
        savedBankAccount: 'Saved Bank Account',
        addNewCard: 'Add New Card',
        addNewBankAccount: 'Add New Bank Account',
        deleteConfirmMessage: (method: string) => `Are you sure you want to delete this ${method}?`,
        deleteBtn: 'Delete',
        cancelBtn: 'Cancel',
        addCreditCardTitle: 'Add Credit Card',
        addCreditCardSubtitle: 'Add Your Credit Card',
        cardHolderLabel: 'Card holder Name',
        cardHolderPlaceholder: 'Enter Card holder Name',
        cardNumberLabel: 'Card Number',
        cardNumberPlaceholder: '0000 0000 0000',
        expiryDateLabel: 'Expiry Date',
        expiryDatePlaceholder: 'MM/YY',
        cvvLabel: 'CVV',
        cvvPlaceholder: '***',
        addCardBtn: 'Add Card',
        updateCardTitle: 'Update Card',
        updateCardBtn: 'Update Card',
        cardAddedSuccess: 'Card added successfully',
        cardUpdatedSuccess: 'Card updated successfully',
      },
      wallet: {
        screenTitle: 'Add Money',
        enterAmount: 'Enter Amount',
        addBtn: 'Add',
        successTitle: 'Payment Process',
        successSubtitle: 'Your payment is being processed. The amount will be added to your account shortly.',
        doneBtn: 'Close',
        failedToAddMoney: 'Failed to add money',
        amountRangeError: (min: number | string, max: number | string, currency: string) => `Amount must be between a minimum of ${formatCurrency(min)} and a maximum of ${formatCurrency(max)}`,
        limitText: (min: number | string, max: number | string, currency: string) => `limit: min ${currency}${min} - max ${currency}${max}`,
      },
    },
    drafts: {
      screenTitle: 'Drafts',
      listTitle: 'Saved as Draft',
      searchPlaceholder: 'Search by job title',
      filterTitle: 'Filter by Date Range',
      fromDate: 'From Date',
      toDate: 'To Date',
      startDate: 'Start Date',
      endDate: 'End Date',
      selectDate: 'Select Date',
      noDraftsFound: 'No draft jobs found',
      noDraftsDesc: "You don't have any saved drafts.",
      savedOn: (date: string) => `Saved on: ${date}`,
    },
    profileDetails: {
      screenTitle: 'Profile Information',
      noProfileFoundTitle: 'Profile Not Found',
      noProfileFoundDesc: 'Could not load profile details at the moment.',
      orgNameLabel: 'Organisation Name',
      contactNameLabel: 'Contact Person Full Name',
      phoneNumberLabel: 'Phone Number',
      emailLabel: 'Email Id',
      addressLabel: 'Company Address',
      categoryLabel: 'Business Category',
      categoryPlaceholder: 'Select Category',
      registrationDocLabel: 'Business Registration Document',
      personalInfo: 'Personal Information',
      businessCategory: 'Business Category',

      saveChanges: 'Save Changes',
      editProfile: 'Edit Profile',
      updateChanges: 'Update Changes',
      verifyEmail: 'Verify Email',
      verifyMobile: 'Verify Mobile',
      mobileVerification: 'Mobile Verification',
      emailVerification: 'Email Verification',
      enterVerificationCode: 'Enter Verification Code',
      emailOtpSubtitle: 'We\'ve sent a 6-digit verification code to your Email Id:',
      mobileOtpSubtitle: 'We\'ve sent a 6-digit verification code to your Phone Number:',
      defaultUser: 'User',
      enterPlaceholder: (label: string) => `Enter ${label}`,
      verify: 'Verify',
      preview: 'Preview',
      notUploaded: 'Not uploaded',
      rejectionNote: 'Note: Required information is missing from the document.',

      pending: 'pending',
      verified: 'Verified',
      pdfDocument: 'PDF Document',
      imageDocument: 'Image Document',
      document: 'Document',
      uploading: 'Uploading...',
      businessRegisterPdf: 'Business_register.pdf',
      invalidPhoneTitle: 'Invalid Phone Number',
      invalidPhoneDesc: 'Please enter a valid 10-digit phone number.',
      emailVerifiedTitle: 'Email Updated',
      emailVerifiedDesc: 'You have successfully updated your email. Please logout and login again with your new email.',
      mobileVerifiedTitle: 'Mobile Verified',
      mobileVerifiedDesc: 'Your phone number has been updated successfully.',
      selectProvinceFirst: 'Please select a province first',
      documentUploadedSuccessfully: 'Document uploaded successfully',
      documentErrorTitle: 'Document Error',
      failedToUploadDocument: 'Failed to upload document',
      validationErrorTitle: 'Validation Error',
      fillMandatoryFields: 'Please fill all mandatory fields',
      uploadMandatoryDocument: 'Please upload the mandatory registration document',
      profileUpdatedSuccessfully: 'Profile updated successfully',
      updateFailedTitle: 'Update Failed',
    },
    inviteContractors: {
      screenTitle: 'Contractors',
      searchPlaceholder: 'Search Contractors',
      selectAll: 'Select All',
      contractorsCount: (count: number) => `Contractors(${count})`,
      sendInvitation: (count: number) => `Send Invitation(${count})`,
      selectionRequired: 'Selection Required',
      selectAtLeastOne: 'Please select at least one contractor to invite.',
      invitationsSent: 'Invitations Sent',
      successMessage: (count: number) => `Successfully sent invitations to ${count} contractors.`,
      noContractorsFound: 'No contractors found for this job.',
      filterBy: 'Filter By',
      clear: 'Clear',
      certifications: 'Certifications',
      selectCertifications: 'Select Certifications',
      minimumRating: 'Minimum Rating',
      cancel: 'Cancel',
      apply: 'Apply',
    },
    contractorProfile: {
      screenTitle: 'Profile Detail',
      experience: 'Experience',
      hourlyRate: 'Hourly Rate',
      availability: 'Availability',
      skills: 'Skills',
      workCategories: 'Work Categories',
      personalInfo: 'Personal Information',
      dateOfBirth: 'Date of Birth',
      email: 'Email',
      certifications: 'Certifications',
      professionalLicense: 'Professional License',
      viewCv: 'View CV',
      invite: 'Invite',
      noCertifications: 'No certifications listed.',
      noLicense: 'No license uploaded',
      resumeNotUploaded: 'Resume not available',
      defaultBio: 'Highly motivated professional with strong observation skills, ensuring safety and security.',
      detailsNotFound: 'Contractor details not found.',
    },
    contractors: {
      screenTitle: 'Contractors',
      searchPlaceholder: 'Search Contractors',
      filterTitle: 'Filters',
      certificationsLabel: 'Certifications',
      selectCertifications: 'Select Certifications',
      minRatingLabel: 'Minimum Rating',
      hourlyRate: (rate: number) => `Hourly Rate: ${formatCurrency(rate)}/h`,
      experience: (years: number) => `Experience: ${years} years`,
      noContractorsFound: 'No contractors found.',
      noContractorsDesc: "We couldn't find any contractors matching your criteria.",
      noJobsFound: 'No job found.',
      noJobsDesc: "We couldn't find any jobs to invite this contractor to.",
      apply: 'Apply',
    },
    reviewInvitation: {
      screenTitle: 'Review Invitation',
      willReceiveInvitation: 'Will Receive Invitation',
      willReceiveInvitationDesc: 'New contractors who will receive invitation',
      alreadyInvited: 'Already Invited',
      alreadyInvitedDesc: 'Already have an invitation for this job',
      notEligible: 'Not Eligible',
      notEligibleDesc: 'Do not meet eligibility criteria',
      failedToFetchSummary: 'Failed to fetch summary',
      somethingWentWrong: 'Something went wrong',
      invitationSent: 'Invitation Sent',
      invitationSentSuccess: 'Successfully sent invitation to contractor.',
      failedToSendInvitation: 'Failed to send invitation',
      invitationSummary: 'Invitation Summary',
      totalSelected: 'Total Selected',
      notePrefix: 'Note: ',
      noteContent: "Only eligible contractors who haven't been invited will receive the invitation.",
      reviewAndSendBtn: 'Review & Send Invitation',
      sendInvitationConfirmTitle: 'Send Invitation?',
      willReceivePrefix: ' contractors will receive invitation for ',
      cancel: 'Cancel',
      yesSend: 'Yes, Send',
      invitationsSentSuccessTitle: 'Invitations Sent!',
      haveBeenInvitedPrefix: ' contractors have been invited for ',
      done: 'Done',
      contractor: 'Contractor',
    },
    disputes: {
      screenTitle: 'Dispute History',
      byClient: 'By Client',
      forClient: 'For Client',

      searchPlaceholder: 'Search Jobs by Job Title ',
      disputeId: 'Dispute ID:',
      transactionId: 'Transaction ID: ',
      disputeTitle: 'Dispute Title',
      disputeDescription: 'Dispute Description',
      noDescription: 'No description provided.',
      viewAttachment: 'View Attachment',
      disputeEvidence: 'Dispute Evidence',
      evidenceNotFound: 'Evidence not found',
      noDisputesFound: 'No disputes found',
      noDisputesDescription: "You don't have any dispute at the moment",
      requiredCertification: 'Required Certification',
      requiredContractor: 'Required Contractor:',
      all: 'All',
      pending: 'Pending',
      settled: 'Settled',
    },
  },
  intro: {
    skip: 'Skip',
    next: 'Next',
    getStarted: 'Get Started',
    slides: [
      {
        title: 'Welcome to GigPay',
        description: 'Connect clients and contractors on one powerful platform for hiring, managing work, and secure payments.',
      },
      {
        title: 'Find Work. Get Paid Faster.',
        description: 'Discover jobs that match your skills, track your work hours, and receive secure payments on time.',
      },
      {
        title: 'Hire Skilled Contractors Easily',
        description: 'Post jobs, manage teams, track progress, and pay contractors securely — all in one place.',
      },
    ],
  },
  locationSearch: {
    screenTitle: 'Search Location',
    placeholder: 'Enter Job Location',
  },
  validation: {
    jobTitleRequired: 'Job title is mandatory',
    jobTitleMinLength: 'Minimum 3 characters mandatory',
    jobTitleAlphanumeric: 'Only alphanumeric allowed',
    descriptionMinWords: 'Minimum 10 words mandatory',
    locationRequired: 'Job location is mandatory',
    fieldRequired: 'Field mandatory',
    minContractors: 'Min 1 mandatory',
    selectAtLeastOne: 'Select at least one Certificate',
    startDatePast: 'Start date cannot be in the past',
    endDatePast: 'End date cannot be in the past',
    endDateBeforeStart: 'End date must be >= start date',
    endTimeBeforeStart: 'End time must be > start time',
    required: 'Required',
    emailRequired: 'Email is mandatory',
    emailInvalid: 'Invalid email address',
    passwordRequired: 'Password is mandatory',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordsMatch: 'Passwords do not match',
    fieldMandatory: (field: string) => `${field} is mandatory`,
    otpExpired: 'OTP has expired. Please request a new one.',
    otpLength: 'Please enter a 6-digit OTP.',
    otpSent: 'A new OTP has been sent to your email.',
    fieldEmpty: 'The field cannot be left empty',
    charRange: (min: number, max: number) => `Character should be between ${min} and ${max}`,
    alphabetsOnly: 'Only alphabets and spaces are allowed',
    cardNumberRange: 'Card number should be between 13 to 19 digits',
    invalidCardNumber: 'Card number must be exactly 16 digits',
    invalidFormat: (format: string) => `Format should be ${format}`,
    invalidMonth: 'Month should be between 01 and 12',
    pastExpiry: 'Expiry date should not be in the past',
    cvvLength: 'CVV should be 3 or 4 digits',
    invalidCvv: 'CVV must be exactly 3 digits',
    termsRequired: 'Please accept the Terms & Conditions and Privacy & Policy.',
    workCategoryRequired: 'Please select a work category',
    selectAtLeastOneSkill: 'Please enter at least one skill',
    maxHourlyRate: (max: number) => `Hourly rate cannot exceed ${formatCurrency(max.toLocaleString())}`,
    availabilityRequired: 'Please select your availability',
    minWords: (field: string, min: number) => `${field} must be at least ${min} words.`,
    maxWords: (field: string, max: number) => `${field} cannot exceed ${max} words.`,
    idTypeRequired: 'Please select an ID type',
    frontImageRequired: 'Front image is mandatory',
    backImageRequired: 'Back image is mandatory',
    selfieRequired: 'Selfie is required',
    invalidImageFormat: 'Please select a JPEG or PNG image.',
    fileTooLarge: (maxSize: number | string, unit: string) => `Please select a file smaller than ${maxSize} ${unit}.`,
    imagePickError: 'Something went wrong while selecting the image.',
    invalidAddress: 'Invalid address.',
    invalidStreetAddress: 'Invalid street address.',
    invalidCity: 'Please enter a valid city name.',
    invalidCountry: 'Please enter a valid country name.',
    selectCertificateRequired: 'Please select a certificate',
    uploadSelectedCertificates: 'Please upload all selected certificates.',
  },
  mock: {
    johnSmith: 'John Smith',
    alexRoyal: 'Alex Royal',
    techCorporate: 'Tech Corporate',
    kelvinDoe: 'Kelvin Doe',
    passwordPlaceholder: 'XXXXXXXX',
    earningFee: (fee: string) => `Admin Fee: ${fee}`,
    version: (v: string) => `GigPay v${v}`,
    jobsCaughtUp: 'You\'re all caught up',
    manageOpportunities: 'Manage your opportunities',
    checkBackLater: 'New job opportunities will appear here. Check back later for updates.',
    securityGuard: 'Security Guard',
    defaultRating: '4.5',
    jobRate: (rate: string) => `${formatCurrency(rate)}/h`,
    defaultAddress: '1234 Maple Street, Springfield, IL 62704, USA',
    defaultDateRange: '10/02/2026 - 12/03/2026',
    defaultTimeRange: '09:00 AM - 05:00 PM',
    jobAbout: 'Part-Time Job Opportunity – Join a Prestigious tech in the UAE.',
    certCpr: '•  CPR Certified',
    certHotel: '•  Hotel Management Certification',
    certOsha: '•  OSHA - 30',
    contractorCount: '2',
  },
  notifications: {
    screenTitle: 'Notifications',
    readAll: 'Read All',
    markAllReadSuccess: 'All notifications marked as read',
    markAllReadFailed: 'Failed to mark notifications as read',
    emptyTitle: 'No Notifications',
    emptySubtitle: "You're all caught up! We'll notify you\nwhen there's something new.",
  },
  tabs: {
    home: 'Home',
    contractors: 'Contractors',
    jobs: 'Jobs',
    wallet: 'Wallet',
    profile: 'Profile',
    matches: 'Matches',
    comingSoon: 'Coming soon',
  },
  security: {
    alertTitle: 'Security Alert',
    jailbrokenWarning: 'For your security, GigPay cannot be used on a rooted or jailbroken device.',
    debugTitle: 'Access Denied',
    debugWarning: 'USB Debugging (ADB) is detected. Therefore, access to the app is restricted.',
    debugSteps: 'Steps to disable USB debugging: Go to Settings > Turn off developer mode',
    closeApp: 'Close App',
  },
  transactionPin: {
    createTitle: 'Create your new transaction PIN',
    confirmTitle: 'Confirm your transaction PIN',
    enterTitle: 'Enter your transaction PIN',
    enterCurrentTitle: 'Enter your current PIN',
    confirmNewTitle: 'Confirm your new PIN',
    enterTransactionPinTitle: 'Please enter the transaction PIN',
    mismatchError: 'PINs do not match. Please try again.',
    samePinError: 'New PIN cannot be the same as your old PIN. Please choose a different PIN.',
    securityFooter: 'This keeps your account secure.',
    setSuccess: 'Transaction PIN set successfully',
    setFailed: 'Failed to set transaction PIN',
    changeSuccess: 'Transaction PIN changed successfully',
    changeFailed: 'Failed to change transaction PIN',
    incorrectPin: 'Incorrect transaction PIN',
    verifyFailed: 'Failed to verify transaction PIN',
    rsaPublicKeyMissing: 'RSA_PUBLIC_KEY is not defined in .env file',
    resetTitle: 'Reset your transaction PIN',
    resetSuccess: 'Transaction PIN reset successfully',
    resetFailed: 'Failed to reset transaction PIN',
    otpSentSuccess: 'OTP sent to your registered email address',
    otpSendFailed: 'Failed to send OTP',
    otpVerifySuccess: 'OTP verified successfully',
    otpVerifyFailed: 'Failed to verify OTP',
    enterOtpSubtitle: 'Enter the 6-digit code sent to',
    resendOtp: 'Resend OTP',
    verifyCode: 'Verify Code',
    resetModalTitle: 'Forget Transaction PIN',
    resetModalSubtitle: 'We will send a 6-digit verification code to your email to verify your identity.',
    resetScreenTitle: 'Reset Transaction PIN',
    createScreenTitle: 'Create Transaction PIN',
    headerPinTitle: 'Transaction PIN',
    forgetModalTitle: 'Forget Transaction PIN',
    forgetModalSubtitle: 'We will send a 6-digit verification code to your email to verify your identity.',
    sendOtpButton: 'Send Verification Code',
    forgetScreenTitle: 'Forget Transaction PIN',
    verifyEmailStep: 'Verify Email',
    enterOtpStep: 'Enter OTP',
    createPinStep: 'Create PIN',
    verifyEmailTitle: 'Verify your email',
    verifyEmailSubtitle: 'We’ll send a 6-digit verification code to your registered email address.',
    registeredEmailLabel: 'Registered email',
    noRegisteredEmail: 'No registered email found for this account.',
    sendOtp: 'Send OTP',
    enterVerificationCodeTitle: 'Enter verification code',
    sentVerificationCodeTo: 'We’ve sent a 6-digit verification code to your registered email:',
    codeExpiredError: 'Verification code has expired. Please request a new OTP.',
    resending: 'Resending...',
  },
  chat: {
    screenTitle: 'Chat',
    defaultRecipient: 'Kelvin Doe',
    today: 'Today',
    yesterday: 'Yesterday',
    typeQueryPlaceholder: 'Type your query here...',
    send: 'Send',
    initialBotMessage: "Hi, we're here to help you.",
    initialUserMessage: 'Today I am not Available to work',
    callPrompt: 'Call',
    calling: 'Calling...',
    chatOptions: 'Chat Options',
    clearChat: 'Clear Chat',
    muteNotifications: 'Mute Notifications',
    blockUser: 'Block User',
    cancel: 'Cancel',
    micPressed: 'Voice message feature coming soon',
    callNotAvailable: 'Phone number not available for this contact',
    chatDisabled: 'This chat is currently read-only',
    chatNotAvailable: 'Chat is not available for this job order',
    noInternetTitle: 'No Internet Connection',
    noInternetDesc: 'No access to chat messages. Please check your internet connection and try again.',
    noInternetAccess: 'No access to chat messages',
    unableToLoadMessages: 'Unable to load messages',
    pullToRefreshOrRetry: 'Pull down to refresh or tap retry.',
    loadFailedDesc: 'Something went wrong while loading messages. Please try again.',
    noInternetRetryNote: 'Network unavailable. Please check your internet connection to retry.',
    retry: 'Retry',
    noChatAvailableTitle: 'No chat available',
    noChatAvailableDesc: 'Start a conversation and your chats will appear here.',
  },
  clockOutRequest: {
    screenTitle: 'Clock Out Request',
    searchPlaceholder: 'Search Jobs by Job Title',
    clockOut: 'Clock Out',
    active: 'Active',
    completed: 'Completed',
    jobRateLabel: 'Job Rate: ',
    proposedRateLabel: 'Proposed Rate: ',
    jobDurationLabel: 'Job Duration:',
    missedClockOutLabel: 'Missed Clock Out :',
    calendarLabel: 'Calender',
    selectDatePlaceholder: 'Select Date',
    clockOutTimeLabel: 'Clock Out',
    selectTimePlaceholder: 'Select Time',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Enter Description',
    submit: 'Submit',
    requestSubmittedSuccess: 'Clock out request submitted successfully',
    pleaseSelectDate: 'Please select a date',
    pleaseSelectTime: 'Please select a time',
    pleaseEnterDescription: 'Please enter description',
    descriptionMinLength: 'Description must be at least 5 characters',
    descriptionMaxLength: 'Description cannot exceed 250 characters',
    noJobsFound: 'No Jobs Found',
    noJobsDesc: 'There are no jobs available for clock out request.',
    noPendingTitle: 'No Pending Clock-Outs',
    noPendingDesc: 'There are no pending jobs available for manual clock out.',
    noRequestedTitle: 'No Requested Clock-Outs',
    noRequestedDesc: 'There are no clock-out requests currently awaiting review.',
    noCompletedTitle: 'No Completed Clock-Outs',
    noCompletedDesc: 'There are no completed manual clock-out requests.',
    jobNotFound: 'Unable to find job details. Please refresh and try again.',
    attendanceNotFound: 'Unable to find attendance record for this job. Please try again.',
    submittedReasonLabel: 'Submitted Reason:',
    rejectionReasonLabel: 'Rejection Reason:',
  },
};

export default strings;
