import { StyleSheet } from 'react-native';
import colors from '@styles/colors';
import fonts from '@assets/Fonts';
import { horizontalScale, verticalScale, fontSize } from '@styles/mixins';

const styles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: colors.white,
    },
    // Search Bar
    searchWrapper: {
        paddingHorizontal: horizontalScale(20),
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(12),
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: horizontalScale(12),
        paddingHorizontal: horizontalScale(14),
        height: verticalScale(46),
    },
    searchIcon: {
        width: horizontalScale(18),
        height: horizontalScale(18),
        tintColor: '#9CA3AF',
        marginRight: horizontalScale(10),
    },
    searchInput: {
        flex: 1,
        fontSize: fontSize(14),
        fontFamily: fonts.regular,
        color: colors.black,
        paddingVertical: 0,
    },
    filterBtn: {
        padding: horizontalScale(4),
        justifyContent: 'center',
        alignItems: 'center',
    },
    filterIcon: {
        width: horizontalScale(20),
        height: horizontalScale(20),
        tintColor: '#6B7280',
    },

    // Job List
    listContent: {
        paddingHorizontal: horizontalScale(20),
        paddingBottom: verticalScale(28),
        paddingTop: verticalScale(4),
    },
    jobCard: {
        backgroundColor: colors.white,
        borderRadius: horizontalScale(16),
        padding: horizontalScale(16),
        marginBottom: verticalScale(16),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#F3F4F6',
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: verticalScale(4),
    },
    jobTitle: {
        fontSize: fontSize(16),
        fontFamily: fonts.bold,
        color: colors.black,
        flex: 1,
        marginRight: horizontalScale(8),
    },
    statusBadge: {
        paddingHorizontal: horizontalScale(10),
        paddingVertical: verticalScale(4),
        borderRadius: horizontalScale(8),
        backgroundColor: '#ECFDF5',
        alignSelf: 'flex-start',
        flexShrink: 0,
    },
    statusText: {
        fontSize: fontSize(12),
        fontFamily: fonts.semiBold,
        color: '#10B981',
    },
    companyName: {
        fontSize: fontSize(13),
        fontFamily: fonts.regular,
        color: '#6B7280',
        marginBottom: verticalScale(8),
    },
    ratingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(8),
    },
    starIcon: {
        width: horizontalScale(14),
        height: horizontalScale(14),
        marginRight: horizontalScale(4),
    },
    ratingText: {
        fontSize: fontSize(12),
        fontFamily: fonts.medium,
        color: '#4B5563',
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(8),
        flexWrap: 'wrap',
        gap: verticalScale(10),
    },
    dateItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    timeItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: horizontalScale(16),
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: verticalScale(8),
    },
    iconSmall: {
        width: horizontalScale(14),
        height: horizontalScale(14),
        marginRight: horizontalScale(8),
        marginTop: verticalScale(2),
        tintColor: '#6B7280',
    },
    infoText: {
        fontSize: fontSize(12),
        fontFamily: fonts.regular,
        color: '#6B7280',
        flexShrink: 1,
    },
    ratesContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        flex: 1,
    },
    strikethroughText: {
        textDecorationLine: 'line-through',
        color: '#9CA3AF',
    },
    proposedRateText: {
        color: '#4B5563',
        marginLeft: horizontalScale(8),
    },
    clockOutBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: horizontalScale(8),
        paddingHorizontal: horizontalScale(14),
        paddingVertical: verticalScale(7),
        marginTop: verticalScale(6),
        backgroundColor: colors.white,
    },
    clockOutIcon: {
        width: horizontalScale(14),
        height: horizontalScale(14),
        marginRight: horizontalScale(6),
        tintColor: colors.black,
    },
    clockOutText: {
        fontSize: fontSize(13),
        fontFamily: fonts.medium,
        color: colors.black,
    },
    reasonRow: {
        backgroundColor: '#F9FAFB',
        borderRadius: horizontalScale(8),
        padding: horizontalScale(10),
        marginTop: verticalScale(8),
        borderLeftWidth: 3,
        borderLeftColor: colors.primary,
        borderRightWidth: 3,
        borderRightColor: colors.primary,
    },
    reasonLabel: {
        fontSize: fontSize(11),
        fontFamily: fonts.semiBold,
        color: '#6B7280',
        marginBottom: verticalScale(2),
    },
    reasonText: {
        fontSize: fontSize(12),
        fontFamily: fonts.regular,
        color: '#374151',
    },
    rejectionReasonRow: {
        backgroundColor: '#FEF2F2',
        borderRadius: horizontalScale(8),
        padding: horizontalScale(10),
        marginTop: verticalScale(8),
        borderLeftWidth: 3,
        borderRightWidth: 3,
        borderLeftColor: '#EF4444',
        borderRightColor: '#EF4444',
    },
    rejectionReasonLabel: {
        fontSize: fontSize(11),
        fontFamily: fonts.semiBold,
        color: '#EF4444',
        marginBottom: verticalScale(2),
    },
    rejectionReasonText: {
        fontSize: fontSize(12),
        fontFamily: fonts.regular,
        color: '#991B1B',
    },

    // Empty state
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(60),
    },
    emptyText: {
        fontSize: fontSize(15),
        fontFamily: fonts.medium,
        color: '#6B7280',
        marginTop: verticalScale(12),
    },
    emptyDesc: {
        fontSize: fontSize(13),
        fontFamily: fonts.regular,
        color: '#9CA3AF',
        marginTop: verticalScale(4),
        textAlign: 'center',
    },

    // Popup Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.55)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: horizontalScale(20),
    },
    modalKeyboardAvoiding: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalCard: {
        width: '100%',
        maxWidth: horizontalScale(380),
        minWidth: horizontalScale(280),
        maxHeight: '88%',
        backgroundColor: colors.white,
        borderRadius: horizontalScale(20),
        paddingHorizontal: horizontalScale(20),
        paddingTop: verticalScale(20),
        paddingBottom: verticalScale(18),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.15,
        shadowRadius: 14,
        elevation: 8,
    },
    modalScrollView: {
        flexGrow: 0,
    },
    modalScrollContent: {
        paddingBottom: 0,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: verticalScale(16),
    },
    modalTitle: {
        fontSize: fontSize(18),
        fontFamily: fonts.bold,
        color: colors.black,
    },
    modalCloseBtn: {
        width: horizontalScale(28),
        height: horizontalScale(28),
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalCloseIcon: {
        width: horizontalScale(26),
        height: horizontalScale(26),
        tintColor: '#1F2937',
    },
    modalInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: verticalScale(16),
    },
    modalInfoCol: {
        flex: 1,
    },
    modalInfoColJob: {
        flex: 1.35,
        marginRight: horizontalScale(10),
    },
    modalInfoColMissed: {
        flex: 1,
    },
    modalInfoLabel: {
        fontSize: fontSize(13),
        fontFamily: fonts.medium,
        color: '#1F2937',
        marginBottom: verticalScale(4),
    },
    modalInfoValueRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    modalInfoIcon: {
        width: horizontalScale(14),
        height: horizontalScale(14),
        marginRight: horizontalScale(5),
        tintColor: '#9CA3AF',
    },
    modalInfoText: {
        fontSize: fontSize(12),
        fontFamily: fonts.regular,
        color: '#6B7280',
        flexShrink: 1,
    },
    modalMissedIcon: {
        width: horizontalScale(14),
        height: horizontalScale(14),
        marginRight: horizontalScale(5),
        tintColor: '#EF4444',
    },
    modalMissedText: {
        fontSize: fontSize(12),
        fontFamily: fonts.medium,
        color: '#EF4444',
        flexShrink: 1,
    },
    fieldLabel: {
        fontSize: fontSize(13),
        fontFamily: fonts.regular,
        color: '#6B7280',
        marginBottom: verticalScale(6),
    },
    datePickerBox: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: horizontalScale(10),
        height: verticalScale(46),
        paddingHorizontal: horizontalScale(14),
        marginBottom: verticalScale(14),
        backgroundColor: colors.white,
    },
    datePickerValue: {
        fontSize: fontSize(14),
        fontFamily: fonts.regular,
        color: colors.black,
    },
    datePickerPlaceholder: {
        fontSize: fontSize(14),
        fontFamily: fonts.regular,
        color: '#9CA3AF',
    },
    datePickerIcon: {
        width: horizontalScale(18),
        height: horizontalScale(18),
        tintColor: '#6B7280',
    },
    descriptionInput: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: horizontalScale(10),
        minHeight: verticalScale(80),
        paddingHorizontal: horizontalScale(14),
        paddingTop: verticalScale(10),
        paddingBottom: verticalScale(10),
        fontSize: fontSize(14),
        fontFamily: fonts.regular,
        color: colors.black,
        textAlignVertical: 'top',
        marginBottom: verticalScale(4),
    },
    descriptionInputError: {
        borderColor: '#EF4444',
    },
    errorText: {
        fontSize: fontSize(12),
        fontFamily: fonts.regular,
        color: '#EF4444',
        marginTop: verticalScale(4),
    },
    charCounter: {
        fontSize: fontSize(12),
        fontFamily: fonts.regular,
        color: '#9CA3AF',
        textAlign: 'right',
        marginBottom: verticalScale(14),
    },
    requiredAsterisk: {
        color: '#EF4444',
    },
    submitBtn: {
        backgroundColor: colors.primary,
        borderRadius: horizontalScale(10),
        height: verticalScale(48),
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: verticalScale(16),
        marginBottom: 0,
    },
    submitBtnText: {
        fontSize: fontSize(16),
        fontFamily: fonts.semiBold,
        color: colors.white,
    },
    // Tabs & Pagination
    tabsContainer: {
        paddingHorizontal: horizontalScale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(12),
    },
    staticFieldBox: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: horizontalScale(10),
        height: verticalScale(46),
        paddingHorizontal: horizontalScale(14),
        marginBottom: verticalScale(14),
        backgroundColor: colors.white,
    },
    staticFieldValue: {
        fontSize: fontSize(14),
        fontFamily: fonts.medium,
        color: colors.gray,
    },
    staticFieldIcon: {
        width: horizontalScale(18),
        height: horizontalScale(18),
        tintColor: '#9CA3AF',
    },
    footerLoader: {
        paddingVertical: verticalScale(16),
        alignItems: 'center',
        justifyContent: 'center',
    },
});

export default styles;
